-- Seed profesores/colaboradores from the report
-- Password rule: correo local-part + 123
-- Example: "maguerbi@csfr.cl" -> "maguerbi123"

INSERT INTO public.usuarios (email, nombre, password, rol, created_at, updated_at)
SELECT
  v.email,
  v.nombre,
  split_part(lower(v.email), '@', 1) || '123',
  'profesor',
  now(),
  now()
FROM (
  VALUES
    ('maguerbi@csfr.cl', 'Aguerbi Hedi Mohamed'),
    ('raguirre@csfr.cl', 'Aguirre Urbina Rousse-Mary Andrea'),
    ('lalonso@csfr.cl', 'Alonso Hafelin Maria Loreto'),
    ('nalvarez@csfr.cl', 'Alvarez Gomez Nestor Ignacio'),
    ('cansoleaga@csfr.cl', 'Ansoleaga Vidal Carolina Paz'),
    ('marias@csfr.cl', 'Arias Abarza Mauricio Alejandro'),
    ('yastudillo@csfr.cl', 'Astudillo Muñoz Yoselyn Andrea'),
    ('rbanderas@csfr.cl', 'Banderas Macaya Ramiro Ignacio'),
    ('pbarckhahn@csfr.cl', 'Barckhahn Berrios Maria Paulina'),
    ('jbascunan@csfr.cl', 'Bascuñan Quezada Javiera Paz'),
    ('mbidart@csfr.cl', 'Bidart Labra Macarena Marcela'),
    ('abilliard@csfr.cl', 'Billiard Gonzalez Paula Anastasia'),
    ('cbirke@csfr.cl', 'Birke Vidal Carolina Beatriz'),
    ('jcadena@csfr.cl', 'Cadena Mella Jorge Salvador'),
    ('bcamacho@csfr.cl', 'Camacho Opazo Beatriz Alejandra'),
    ('acampos@csfr.cl', 'Campos Vallette Maria Alicia'),
    ('ccampusano@csfr.cl', 'Campusano Lobos Carolina Andrea'),
    ('dcanelo@csfr.cl', 'Canelo Aravena Daniela Michelle'),
    ('scarrillo@csfr.cl', 'Carrillo Diaz Soledad Lorena'),
    ('acarrizo@csfr.cl', 'Carrizo Ortiz Analucia'),
    ('pcarvajal@csfr.cl', 'Carvajal Santander Paulina'),
    ('lcastillo@csfr.cl', 'Castillo Hernandez Luis Alejandro'),
    ('gcastillo@csfr.cl', 'Castillo Ortiz Gleisa Carolina'),
    ('pcerda@csfr.cl', 'Cerda Cordero Paola Angélica'),
    ('pchacana@csfr.cl', 'Chacana Barrales Patricia Del Carmen'),
    ('mchacon@csfr.cl', 'Chacon Garcia Maiyeling Margaret'),
    ('dchaparro@csfr.cl', 'Chaparro Perey Maria Dominga'),
    ('vcid@csfr.cl', 'Cid Henriquez Valentina Ignacia'),
    ('ccoll@csfr.cl', 'Coll Barrios Catalina Sofia'),
    ('dcortes@csfr.cl', 'Cortes Hurtado Diego Felipe'),
    ('ccubillos@csfr.cl', 'Cubillos Bacigalupo Catalina'),
    ('scubillos@csfr.cl', 'Cubillos Mas Sonia Andrea'),
    ('cdelabarrera@csfr.cl', 'De La Barrera Contreras Cristián Eduardo'),
    ('cdelamaza@csfr.cl', 'De La Maza Rosas Claudia Elena'),
    ('pdiaz@csfr.cl', 'Diaz Leon Pamela Soledad'),
    ('cdiaz@csfr.cl', 'Diaz Oyarzo Carolina Isabel'),
    ('edonoso@csfr.cl', 'Donoso Gatica Eugenio Jose'),
    ('megana@csfr.cl', 'Egaña Rivera Maria Teresa'),
    ('melgueta@csfr.cl', 'Elgueta Herrera Maria De Los Angeles'),
    ('selortegui@csfr.cl', 'Elortegui Francioli Sergio Alberto'),
    ('cfernandez@csfr.cl', 'Fernandez Cerda Christian Freddy'),
    ('dfuentes@csfr.cl', 'Fuentes Arriagada Daniela Francisca'),
    ('pfuentes@csfr.cl', 'Fuentes Wingberg Pilar Dagne'),
    ('pgandolfo@csfr.cl', 'Gandolfo Costa Sandra Paola'),
    ('mgarrido@csfr.cl', 'Garrido Ruiz-Tagle Maria Macarena'),
    ('pgautier@csfr.cl', 'Gautier Vera Pablo Alberto'),
    ('kgodoy@csfr.cl', 'Godoy Ibaceta Kevin Andres'),
    ('mgomez@csfr.cl', 'Gomez Campos Maria Alicia'),
    ('vgomez@csfr.cl', 'Gomez Llorente Maria Vicenta'),
    ('jgonzalez@csfr.cl', 'Gonzalez Villarroel Jessica Silvana'),
    ('pherrrera@csfr.cl', 'Herrera Selanio Paulina Francisca'),
    ('thuber@csfr.cl', 'Huber Perez Tamara Yael'),
    ('mjarpa@csfr.cl', 'Jarpa Parr María Magdalena'),
    ('mjimenez@csfr.cl', 'Jimenez Segovia Macarena Paz'),
    ('pkrippel@csfr.cl', 'Krippel Ponce De Leon Paulina'),
    ('clagos@csfr.cl', 'Lagos Quevedo Catalina Florencia'),
    ('ilarranaga@csfr.cl', 'Larrañaga Silva Isabel Francisca'),
    ('jlazcano@csfr.cl', 'Lazcano Schirmer Joaquin Andres'),
    ('bleniz@csfr.cl', 'Leniz Diaz Bernardita Verónica'),
    ('ploosli@csfr.cl', 'Loosli Bustamante Patricia Eugenia'),
    ('mlopez@csfr.cl', 'Lopez  Mariela Del Valle'),
    ('alopez@csfr.cl', 'Lopez Barboza Aixa Carolina'),
    ('glopez@csfr.cl', 'López Cepeda Gloria Solange'),
    ('aluer@csfr.cl', 'Luer Sanhueza Andrea Valentina'),
    ('cmagana@csfr.cl', 'Magaña Colombo Carla Nadia'),
    ('smaldonado@csfr.cl', 'Maldonado Arenas Silvia De Las Mercedes'),
    ('mmalo@csfr.cl', 'Malo Fernandez Macarena Del Pilar'),
    ('nmartinez@csfr.cl', 'Martinez Astudillo Nataly Nicolee'),
    ('amartinez@csfr.cl', 'Martinez Gonzalez Aida Leonor'),
    ('emartinez@csfr.cl', 'Martinez Gonzalez Eduardo Juan'),
    ('tmartinez@csfr.cl', 'Martinez Gonzalez Tatiana Del Carmen'),
    ('cmartinez@csfr.cl', 'Martinez Ortiz Camila Fernanda'),
    ('mmaturana@csfr.cl', 'Maturana Gonzalez Maria Paz'),
    ('lmendoza@csfr.cl', 'Mendoza Hoyng Luis Alberto'),
    ('amorales@csfr.cl', 'Morales Lira Antonia'),
    ('lmouat@csfr.cl', 'Mouat Peña Lorena Ignacia'),
    ('mmuzio@csfr.cl', 'Muzio Vitali Maddalena Alessandra'),
    ('mnavarrete@csfr.cl', 'Navarrete Urbano Myriam Luz'),
    ('anavarro@csfr.cl', 'Navarro Villegas Angelica Maria'),
    ('rneumann@csfr.cl', 'Neumann De L´¨ Herbe Rommy Angele'),
    ('manunez@csfr.cl', 'Nuñez Muñoz Manuel Alejandro'),
    ('folivarez@csfr.cl', 'Olivarez Caceres Flor Maria'),
    ('jortega@csfr.cl', 'Ortega Escola Jesus Alfredo'),
    ('cortuzar@csfr.cl', 'Ortúzar Walker Catalina Fernanada'),
    ('ependas@csfr.cl', 'Pendas Arancibia Elena De Los Angeles'),
    ('dperez@csfr.cl', 'Perez Garces Diego Patricio'),
    ('apinochet@csfr.cl', 'Pinochet Raviola Ana Maria'),
    ('dpolmmann@csfr.cl', 'Pollmann Roig Dominique'),
    ('lponce@csfr.cl', 'Ponce Silva Lilian Ninoska'),
    ('mprieto@csfr.cl', 'Prieto Olavarría María Cristina'),
    ('aquezada@csfr.cl', 'Quezada Boetsch Angela'),
    ('equezada@csfr.cl', 'Quezada Montecinos Evelyn Marcela'),
    ('rramirez@csfr.cl', 'Ramirez Basualdo Ricardo Andres'),
    ('mretamales@csfr.cl', 'Retamales Cortes Maria Jose'),
    ('creveco@csfr.cl', 'Reveco Pugh Catalina Paz'),
    ('krippley@csfr.cl', 'Rippley Varas Katherine'),
    ('brodriguez@csfr.cl', 'Rodriguez Doren Benjamin Jose'),
    ('crodriguez@csfr.cl', 'Rodriguez Sainte-Marie Catalina'),
    ('crojas@csfr.cl', 'Rojas Campos Christian Andres'),
    ('cromero@csfr.cl', 'Romero Reyes Carolina Paz'),
    ('mrosende@csfr.cl', 'Rosende Pirazzoli Maria Elsa'),
    ('mruiz@csfr.cl', 'Ruiz Wiegand Maria De Los Angeles'),
    ('csanchez@csfr.cl', 'Sanchez Sanchez Carlos Aurelio'),
    ('gsanhueza@csfr.cl', 'Sanhueza Arancibia Gonzalo Hernan'),
    ('dschiavetti@csfr.cl', 'Schiavetti Brunet Daniela'),
    ('csepulveda@csfr.cl', 'Sepulveda Dominguez Carolina'),
    ('csheward@csfr.cl', 'Sheward Giordano Carolina Pia'),
    ('mstraube@csfr.cl', 'Straube Quintanilla Marlene Falide'),
    ('pvaldes@csfr.cl', 'Valdes Verdugo Paulo Milenko'),
    ('mvalenzuela@csfr.cl', 'Valenzuela Gonzalez Maria Jose'),
    ('dvaras@csfr.cl', 'Varas Hurtado Daniela Lissette'),
    ('evasquez@csfr.cl', 'Vasquez Cunich Maria Eugenia'),
    ('cvasquez@csfr.cl', 'Vasquez Perez Carolina Cecilia'),
    ('rvasquez@csfr.cl', 'Vasquez Yañez Roberto Honorino'),
    ('rvergara@csfr.cl', 'Vergara De Larraechea Rosario'),
    ('avidal@csfr.cl', 'Vidal Arancibia Andrea Carolina'),
    ('vvielma@csfr.cl', 'Vielma Silva Valentina Paz'),
    ('vvillouta@csfr.cl', 'Villouta Mery Viviana Paz'),
    ('twiedmaier@csfr.cl', 'Wiedmaier Venegas Tania Belen'),
    ('syianatos@csfr.cl', 'Yianatos Piraino Stefania Anna'),
    ('cybini@csf.cl', 'Yubini Lagos Carolina Paz')
) AS v(email, nombre)
ON CONFLICT (email) DO UPDATE
SET nombre = EXCLUDED.nombre,
    password = EXCLUDED.password,
    rol = EXCLUDED.rol,
    updated_at = now();
